### ISSUE TITLE
When signed in - change 'Get Quote' to "Get estimate" (same as #93 when not logged in)

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#102]

**Comment by Pikapangokev** [comment]
![screen shot 2016-11-07 at 22 29 04](https://cloud.githubusercontent.com/assets/22468878/20078886/3f8c0eea-a53a-11e6-8282-a0004414fdaf.png)

**Comment by neilpie** [comment]
Will be closed by #93
