### ISSUE TITLE
When signed in - change 'collect & deliver' wording to 'Pick up & drop off' wording (same as #90)

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#103]
To keep continuity throughout site

**Comment by Pikapangokev** [comment]
![screen shot 2016-11-07 at 22 29 04](https://cloud.githubusercontent.com/assets/22468878/20078876/323cfe34-a53a-11e6-960a-1d67610a3ad9.png)

**Comment by neilpie** [comment]
This will be fixed by #90

**Comment by neilpie** [comment]
Will be closed  y #90
