### ISSUE TITLE
New link when signed in on homepage below new 'Get Estimate' button

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#104]
![screen shot 2016-11-07 at 22 34 11](https://cloud.githubusercontent.com/assets/22468878/20078946/6d283518-a53a-11e6-9082-eae045523590.png)

**Comment by Pikapangokev** [comment]
There needs to be a link straight to exact quote, so they don't have to do an estimate
The link in the user side bar goes to the exact quote page (Create quote)
![screen shot 2016-11-07 at 22 39 31](https://cloud.githubusercontent.com/assets/22468878/20079095/1875a3a6-a53b-11e6-98c6-1f617c571ceb.png)

**Comment by Pikapangokev** [comment]
Can a link to the exact quote be inserted under the 'Get Estimate' button?

Hope this makes sense. For a new client they have to enter the same postcodes 3 time before getting the exact quote sent off to the driver. We can reduce this by placing the exact quote link on this page.

**Comment by neilpie** [comment]
If we add this in a similar way to the 'sign in' link on the logged out homepage, so it would read 

GET ESTIMATE
or create a quote
