### ISSUE TITLE
On completion of driver updating price, the client receives 2 identical emails alerting them to the update

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#105]
Just need to make this one email getting sent out

**Comment by neilpie** [comment]
@Pikapangokev I can't replicate this in staging, but am sure we saw it happening when you were in the office. As such I am going to test a quote on live.

**Comment by neilpie** [comment]
@Pikapangokev After testing on Live  I still cannot replicate this.

The only time a second email would be sent is if the Estimate amount is entered, saved and then subseqently changed and saved again...

Are you able to replicate yourself?

**Comment by neilpie** [comment]
@leglesslizard 

When the quote meta is first updated, if the field that has been updated is the estimate amount, then 2 emails are sent.

If the field is something else, like driver notes then when the estimate amount is subsequently added, only 1 email is sent.

Could you investigate on your return, please?

**Comment by leglesslizard** [comment]
This was due to a workaround needed to ensure we had a user ID before quote meta was restructured. Removing this fixed the issue
