### ISSUE TITLE
When signed in, quotes with 1 postcode outside area, [submit more information] button not linked to anything

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#122]
![screen shot 2016-11-13 at 15 32 26](https://cloud.githubusercontent.com/assets/22468878/20246807/f4794fcc-a9b6-11e6-8a67-edc9e2c4ba10.png)
![screen shot 2016-11-13 at 15 32 33](https://cloud.githubusercontent.com/assets/22468878/20246808/f47c2a3a-a9b6-11e6-93fd-c552eda5ff8d.png)

**Comment by neilpie** [comment]
as per #123 this goes to the signup form for me. Can you double check, please?

**Comment by neilpie** [comment]
@Pikapango fix is in staging
