### ISSUE TITLE
When signed in, quotes with both postcodes outside area, [get notified] button doesn't go anywhere

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#123]
![screen shot 2016-11-13 at 15 32 57](https://cloud.githubusercontent.com/assets/22468878/20246815/230918cc-a9b7-11e6-929a-63abc8886354.png)
![screen shot 2016-11-13 at 15 32 53](https://cloud.githubusercontent.com/assets/22468878/20246816/230cb09a-a9b7-11e6-8ae1-bdcb25e63df8.png)

**Comment by neilpie** [comment]
@Pikapangokev 

This *should* go to the registration form. It certainly does for me. 

<img width="1095" alt="screenshot 2016-11-13 17 48 51" src="https://cloud.githubusercontent.com/assets/488297/20247658/7e6a1da8-a9c9-11e6-9bd1-2d5236d58e8f.png">

I think the UX might be a bit confusing, so perhaps we could make a textual change to make this clearer?

**Comment by neilpie** [comment]
@Pikapangokev - This was a bug caused when I cleaned out some old code, wihtout realising that it was still being called here. Fix has been shipped to staging
