### ISSUE TITLE
When signed in, exact quote both codes outside area, needs text alteration

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#124]
![screen shot 2016-11-11 at 18 03 08](https://cloud.githubusercontent.com/assets/22468878/20246833/5dbde01a-a9b7-11e6-9efb-851bfdc701cd.png)

Change text to read;
“Grrr, we don’t currently operate in these postcode(s). We’re growing fast though and will make sure to let you know when we do. Sit tight and someone will get back to you shortly”

**Comment by neilpie** [comment]
@Pikapangokev Fix is in staging
