### ISSUE TITLE
User side bar not showing new quote until refresh page, can page auto refresh at this point?

### ISSUE THREAD

**Issue by neilpie** [pie/PikaPango#30]

**Comment by Pikapango** [comment]
Once a quote had been accepted by customer, it should appear in the sidebar as active.
Can the page auto refresh when customer accepts so the side bar active quote appears?
It does sound confusing I know

**Comment by neilpie** [comment]
This should be possible

**Comment by neilpie** [comment]
@Pikapangokev if you wish this to be added as a quick fix, we can just force an entire page reload, but a smoother integration will require a bit more of a refactor and take a little time

**Comment by neilpie** [comment]
@Pikapangokev this works quite nicely, although it would be better to revisit on a subsequent round of dev
