### ISSUE TITLE
Payment page shows £50 estimate speech at bottom 

### ISSUE THREAD

**Issue by neilpie** [pie/PikaPango#36]

**Comment by neilpie** [comment]
Do we mean the following? If so, then this is intended, surely?

<img width="643" alt="screenshot 2016-09-21 14 35 14" src="https://cloud.githubusercontent.com/assets/488297/18712991/ad36da30-8008-11e6-836c-b7ea71016436.png">

**Comment by Pikapango** [comment]
Hi Neil. Our plan for charges is this. £25 for 1st half hour. £40 per hour after this time in 30min increments. i.e. 30mins = £25, 1hr = £40, 1.5hrs = £60, 2hrs = £80, 2.5hrs = £100 etc.....
All estimates should be in denominations of these values only.
The sentence below the PAY LATER Box probably doesn't need to be there if the estimate is accurate.

**Comment by Pikapangokev** [comment]
When entering postcodes to quote page, if I do not leave a space between the numbers it gives the message pasted below. Do we need to have a space or can this be easily changed?
![screen shot 2016-09-27 at 10 21 40](https://cloud.githubusercontent.com/assets/22468878/18867512/7129b4a2-849c-11e6-9f75-9fd95b543088.png)

**Comment by neilpie** [comment]
I'll add the Estimate formula change to another ticket, and leave this one for removing the text - to be clear, we want it removed completely? Should we leave "Quote is an estimate. Actual cost may vary depending on the load" ?

**Comment by Pikapangokev** [comment]
Yes, please leave "quote is an estimate. Actual cost may vary depending on the load"
