### ISSUE TITLE
Implement Sendgrid for email deliverability

### ISSUE THREAD

**Issue by neilpie** [pie/PikaPango#41]

**Comment by neilpie** [comment]
I have emailed Kevin and Stanley with regards to setting up CNAME DNS records for this

**Comment by Pikapango** [comment]
I signed in to change CNAME DNS, got to the screen but was unsure if I have done it right. Sorry Neil, I have emailed you the login details so you can quickly add for us if you don't mind?

**Comment by neilpie** [comment]
@pie/developers we can take care of this i think

**Comment by Zeebad** [comment]
@neilpie This is set up on staging using stanley.wilson@pikapango.com as the sending email, let me know if it should be something else. Test email arrived in around 30 seconds.

Using pie sendgrid account with "pikapango" API key

**Comment by Zeebad** [comment]
DNS added

**Comment by neilpie** [comment]
Shipped to live
