### ISSUE TITLE
Double check miniquote formula

### ISSUE THREAD

**Issue by neilpie** [pie/PikaPango#43]
Hi Neil. Our plan for charges is this. £25 for 1st half hour. £40 per hour after this time in 30min increments. i.e. 30mins = £25, 1hr = £40, 1.5hrs = £60, 2hrs = £80, 2.5hrs = £100 etc.....
All estimates should be in denominations of these values only.
The sentence below the PAY LATER Box probably doesn't need to be there if the estimate is accurate.

**Comment by neilpie** [comment]
Reported in #36

**Comment by leglesslizard** [comment]
Adjusted accordingly but waiting on clarification of the following:
- Are we ditching the additional 30minutes time for pick up and drop off?
- Is this always rounded up as before; to the nearest half hour?
