### ISSUE TITLE
Payment notification emails contain bad link

### ISSUE THREAD

**Issue by neilpie** [pie/PikaPango#45]
@leglesslizard the emails coming out when a payment is made are missing the Quote ID from the URL

A payment has been made for quote . To see details please click here - http://pikapango.staging.wpengine.com/wp-admin/post.php?post=&action=edit

**Comment by leglesslizard** [comment]
Added a fallback in case the post ID isn't returned. Need to see what the IPN data array is giving us here as the "item_number" value should be the quote ID. Obviously, this isn't getting through anymore for some reason

**Comment by leglesslizard** [comment]
Tested with pre-made paypal form and comes through OK. Need to check the <input> item_number exists and contains the right data on front end form

**Comment by neilpie** [comment]
Works on live also with a full payment. Closing
