### ISSUE TITLE
After resetting password the screen instructs: 'Back to homepage'. Instead, can this command read 'Log in now' and redirect to the log in page (not the home page)

### ISSUE THREAD

**Issue by neilpie** [pie/PikaPango#5]
After resetting password the screen instructs: 'Back to homepage'. Instead, can this command read 'Log in now' and redirect to the log in page (not the home page)

**Comment by Pikapangokev** [comment]
I think this is referenced with a picture on the google sheet, it is just a case of changing the wording inside the orange box

**Comment by neilpie** [comment]
Are you able to look into this @leglesslizard  ?

I think it could just need a couple of filters added into your custom login plugin

**Comment by leglesslizard** [comment]
This has already been implemented in the plugin and is up on staging:

<img width="460" alt="screen shot 2016-10-13 at 12 56 50" src="https://cloud.githubusercontent.com/assets/6690398/19348204/a79d2622-9144-11e6-85f5-6edd8ec89007.png">

And this redirects to login page.

**Comment by leglesslizard** [comment]
Is any further action required here?
