### ISSUE TITLE
Next page - Enter details page (not signed in)

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#50]
When clicking “Terms and Conditions’ wording next to checkbox the page goes to about blank

Terms and conditions page need to be attached to this hyperlink when we have finished them

**Comment by Pikapangokev** [comment]
When all information is entered and checkbox is ticked, I click SUBMIT and the page doesn’t go anywhere

**Comment by neilpie** [comment]
Ts & Cs link is dealt with in #61 but this raises the issue - do we need the Ts & Cs to be checked when a user rgisters *and* creates a quote?

**Comment by Pikapangokev** [comment]
Yes please as this binds them to our t&c's, payment terms, extra charges etc
