### ISSUE TITLE
Exact quote 2

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#52]
CT4 postcode came up as out of our target area, then went to upload photo page, as a result, page 2 doesn't offer T&C checkbox

Add CT4 as a postcode within our range. Have the out of our postcode speech after page 2 of exact quote so T&C can be ticked

It means that at the back end we can't complete quote

**Comment by Pikapangokev** [comment]
![screen shot 2016-10-11 at 12 19 04](https://cloud.githubusercontent.com/assets/22468878/19268595/31bfd5fa-8fad-11e6-9549-a43fce44b0e9.png)

**Comment by neilpie** [comment]
Ah I see the issue here, but is the solution not to allow you to edit a quote in the backend if the Ts & Cs have not been checked?

**Comment by Pikapangokev** [comment]
So, there are 2 pages to exact quote. First page is load, drop off & pickup, date, time....when NEXT is clicked at the bottom the quote automatically comes through to the back end before the UPLOAD PHOTO, T&C'S AND SUBMIT. 
I think the quote should come through to driver after both pages are completed

**Comment by neilpie** [comment]
#64
