### ISSUE TITLE
Get Estimated travel time

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#54]
Enter date and time, nothing happened for sand-bag quote

fix estimated travel time function

**Comment by neilpie** [comment]
@leglesslizard this seems to be crapping out on the postcodes.

**Comment by Pikapangokev** [comment]
![screen shot 2016-10-11 at 12 44 13](https://cloud.githubusercontent.com/assets/22468878/19269124/8950e5cc-8fb0-11e6-8f21-b7667bfa8594.png)

**Comment by neilpie** [comment]
@Pikapangokev @leglesslizard hold on this. I programmed in some better sanitise rules for postcodes, and these may not have been shiped.p

**Comment by Pikapangokev** [comment]
okay

**Comment by neilpie** [comment]
@Pikapangokev the Postcode validation is fixed, but we still get an invalid parameter for Colection Time. I am asking @leglesslizard to investigate

`{"headers":{},"body":"{\"code\":\"rest_invalid_param\",\"message\":\"Invalid parameter(s): collectionTime\",\"data\":{\"status\":400,\"params\":{\"collectionTime\":\"Invalid parameter.\"}}}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}`

**Comment by leglesslizard** [comment]
Altered validation callback for collection time. Should be good to go now
