### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#55]
Contact name of account holder does not appear in quote details. This is because I left the field blank when entering details for exact quote (it said to ‘leave blank if its you’, so I did)

fix this so either the details are auto entered on submission of quote or take out the ‘leave blank if its you’ prompt

**Comment by Pikapangokev** [comment]
![screen shot 2016-10-11 at 12 19 36](https://cloud.githubusercontent.com/assets/22468878/19268658/90674c0a-8fad-11e6-859b-509f87a53370.png)

**Comment by neilpie** [comment]
@Pikapangokev this pulls in from the name when the account is registered. Also addressing in #62
