### ISSUE TITLE
Update quote

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#56]
I could not update quote as the T&C checkbox had not been ticked by customer

**Comment by neilpie** [comment]
What is the issue here @Pikapangokev ? If a customer has not ticked the Ts & Cs then a quote should not be updated.

**Comment by Pikapangokev** [comment]
If they do not know this process then they will never get an answer from me.
I guess that best solution is to not let client click SUBMIT on page 2 until the box is checked

**Comment by neilpie** [comment]
@leglesslizard can we make the T&C box not required in the admin, please?

**Comment by leglesslizard** [comment]
@neilpie removed the required parameter on this. I'm unclear on the issue here exactly so let me know if there is more to do.
