### ISSUE TITLE
Uploading photo doesn't work

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#58]

**Comment by Pikapangokev** [comment]
Cant complete quotes to view payment options

**Comment by Pikapangokev** [comment]
![screen shot 2016-10-11 at 12 19 22](https://cloud.githubusercontent.com/assets/22468878/19268679/a69d5a5a-8fad-11e6-8870-a19112250b7a.png)

**Comment by neilpie** [comment]
@Pikapangokev can yo confirm that this actually doesn't work, and isn't just taking a long time, please?

Agreed that if it is taking so long that it seems broken then it's an issue, but it's a different issue to it not working at all. For me, if I upload an image then it goes in.

**Comment by neilpie** [comment]
This is definitely working, but a 4MB image took 2.2 minutes to upload for me (see attached)

This is clearly an issue and I'm investigating with WPE

<img width="738" alt="screenshot 2016-10-12 12 59 57" src="https://cloud.githubusercontent.com/assets/488297/19309326/1230cb52-907c-11e6-935d-d6e653812565.png">

**Comment by neilpie** [comment]
Noting that this took 1.3 minutes to upload the same image via WP-admin

**Comment by neilpie** [comment]
It seems Subscribers to not have permission to upload media - @leglesslizard did we not add this?

**Comment by neilpie** [comment]
Of note, to upload files via API we require both the `upload_files` and the `edit_posts` capabilities
