### ISSUE TITLE
Customer info doesn't carry across to the back end admin

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#59]
Customer information is not entered
Pick up info not carried over fully, no phone number, date wrong, AM wrong (specified ANYTIME)
Drop off info not carried over, just address
t&c checkbox unchecked so cant update quote
get estimated travel time not working

**Comment by Pikapangokev** [comment]
The problem is that there is nowhere for the customer to enter these details. Basically each account is just an email address with no accompanying information.
This means when the field says, leave blank if its you, nothing is is carried over

**Comment by Pikapangokev** [comment]
![screen shot 2016-10-11 at 12 19 36](https://cloud.githubusercontent.com/assets/22468878/19268685/b6aa81e8-8fad-11e6-8e2f-951732775aba.png)

**Comment by neilpie** [comment]
Hi Kev

When a user registers, they are required to give us Their Full Name as per this form:

<img width="342" alt="screenshot 2016-10-12 13 34 04" src="https://cloud.githubusercontent.com/assets/488297/19310532/6be3cf18-9082-11e6-878e-e742008cf7fc.png">

I think when we register users internally then we must also add this data and it should pull through. 

@PikapangoKev - how did you register Morris Healy?

I notice that the 'register' link by the sign in form takes the user to a register page that does not reflect the form we wish to use - I need to get @leglesslizard to add this redirect. (issue #62)

I am double checking the inconsistency in the data

**Comment by Pikapangokev** [comment]
I think I just went to a page like this, stupidly I didn't record it and I have run out of email addresses to register with. The issue was that when the exact quote came to back end, no details carried over to the quote content. In fact, even when I added details in the exact quote page 1, the details still didn't carry over

**Comment by neilpie** [comment]
Should be fixed by #62
