### ISSUE TITLE
Set up new quote - IBC TANK from there to my house

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#60]
first page fine, again, photo would not upload, couldn’t click GET QUOTE as a result. I did receive an email Admin End after clicking NEXT on page 1. Also, quote appears in client toggle bar after clicking next. 
This means no photo, no special instructions can be added

Terms of service link goes to get quote homepage

**Comment by Pikapangokev** [comment]
![screen shot 2016-10-11 at 12 19 29](https://cloud.githubusercontent.com/assets/22468878/19268695/c200cc6e-8fad-11e6-9274-7366499cedf1.png)

**Comment by neilpie** [comment]
@Pikapangokev Terms of service link goes to get quote homepage is now #61

**Comment by neilpie** [comment]
@Pikapangokev what's the clear issue from this ticket, please? 

Is it the quote appearing in the sidebar without the image being added?

**Comment by Pikapangokev** [comment]
@neilpie , Because upload photo didn't complete, I could not click get quote button to complete the exact quote

**Comment by Pikapangokev** [comment]
The quote appeared in the side bar after clicking NEXT on page 1, before uploading a photo, checking t&cs

**Comment by neilpie** [comment]
Hi @Pikapangokev 

This is actually by design. If a user is on a slow connection, they may experience difficulty uploading images or similar which means they can come back at a later date (when in the office, for example) and upload an image then to complete the quote.

**Comment by neilpie** [comment]
Note - I believe we are addressing the possibly related issue in #64
