### ISSUE TITLE
Terms of service link goes to get quote homepage

### ISSUE THREAD

**Issue by neilpie** [pie/PikaPango#61]
As title

**Comment by neilpie** [comment]
@PikapangoKev - do we have a Ts&Cs page set up yet?

**Comment by Pikapangokev** [comment]
I have in excel spreadsheet, have passed to Stan for approval and editing but we are nearly there.
Can we add a page to the mini burger stack on homepage? Then add the content when finished?

**Comment by neilpie** [comment]
Redirect links to /terms-conditions
