### ISSUE TITLE
Make native register form redirect to App

### ISSUE THREAD

**Issue by neilpie** [pie/PikaPango#62]
The register link in the attached image, and the URL http://pikapango.staging.wpengine.com/wp-login.php?action=register need to redirect to http://pikapango.staging.wpengine.com/#/registerforquote

<img width="436" alt="screenshot 2016-10-12 13 52 36" src="https://cloud.githubusercontent.com/assets/488297/19310683/3c339bc6-9083-11e6-87f5-90d81665132b.png">

**Comment by Pikapangokev** [comment]
This is wthe page I came to registering Morris Healy

**Comment by leglesslizard** [comment]
I have adjusted the register link to point to the given URL

**Comment by neilpie** [comment]
@leglesslizard is there a way to hook in and force http://pikapango.staging.wpengine.com/wp-login.php?action=register to redirect as well?

**Comment by leglesslizard** [comment]
Added a redirect on page load if user is on registration page

**Comment by neilpie** [comment]
THis has come back

**Comment by neilpie** [comment]
@Pikapangokev this is now back in place
