### ISSUE TITLE
New Quote notification should go when Ts & Cs checked

### ISSUE THREAD

**Issue by neilpie** [pie/PikaPango#64]
@leglesslizard At the moment we send a new quote notification to Admin/Driver when a quote is created, but this actually happens *before* images are uploaded and the Ts&Cs are checked. 

Could we defer this email until the quote is updated from the front end and the Ts & Cs have been checked, please?

**Comment by leglesslizard** [comment]
@neilpie would we be able to drop in a hook here for exactly when you want the emails to go out. It's very awkward with regards to using the current setup (quote is created without the info we need, update postmeta doesn't seem to be firing...)

I'm just unsure of where to drop the hook (obviously tried on create quote but that fires too early)

**Comment by neilpie** [comment]
@leglesslizard I think they should go out on update post, like we do when the Estimate amount is changed. Is that not do-able?

**Comment by leglesslizard** [comment]
Have updated as discussed. Now fires after terms of service has been checked
