### ISSUE TITLE
Estimate date does not parse correctly in widget

### ISSUE THREAD

**Issue by neilpie** [pie/PikaPango#65]
@leglesslizard 

When we make an Estimate in the quote edit screen, it shows the date correctly, but when the page is reloaded and the estimate is loaded into the widget, the date is not really clear.

see attached
<img width="293" alt="screenshot 2016-10-13 20 07 00" src="https://cloud.githubusercontent.com/assets/488297/19363056/d3428e5c-9180-11e6-91b4-171a093927e6.png">
<img width="294" alt="screenshot 2016-10-13 20 05 42" src="https://cloud.githubusercontent.com/assets/488297/19363057/d3441c7c-9180-11e6-9d6c-ad4cb228656a.png">

**Comment by leglesslizard** [comment]
Date now displays correctly in both places, be aware that previous dates may still show the old incorrect formats
