### ISSUE TITLE
Email not sent when signing up 

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#67]
I pretended I was someone who had stumbled onto the site so I wasn't a user and I wasn't signed in. On home page, entered pick up and drop off postcodes, 
![screen shot 2016-10-14 at 10 03 48](https://cloud.githubusercontent.com/assets/22468878/19381960/fc059e86-91f5-11e6-802a-e97f85b285cf.png)
I got the estimate the went on to enter my details
![screen shot 2016-10-14 at 10 05 38](https://cloud.githubusercontent.com/assets/22468878/19381984/0bc984ae-91f6-11e6-825f-faa3d5972669.png)
I then went to this screen
![screen shot 2016-10-14 at 10 05 50](https://cloud.githubusercontent.com/assets/22468878/19381999/1bcfd682-91f6-11e6-911d-bd2487ed1af0.png)
The email never arrived at my inbox.

**Comment by Pikapangokev** [comment]
I got round this by using 'reset password' function on home page.
A link to the password reset came through immediately

**Comment by neilpie** [comment]
Do you know the time of this? I can see two emails in SendGrid as per the attached, but they are 4 seconds apart. 

<img width="1092" alt="screenshot 2016-10-18 13 42 21" src="https://cloud.githubusercontent.com/assets/488297/19478058/e33f214c-9538-11e6-94e8-4ac98726b78f.png">

I'll keep this issue open and hopefully we can crack this one,

**Comment by Pikapangokev** [comment]
My apologies, I pasted the incorrect images.
The email address was thebearded@hotmail.co.uk, 1st email didn't come through but second one did at 22.57pm on 13th October

**Comment by leglesslizard** [comment]
I created new users using 4 emails and all came through correctly so unfortunately I cannot replicate this. This was on the staging site.

The email address @hotmail.com did move the email into my spam folder.

**Comment by neilpie** [comment]
Hi @Pikapangokev 

Can you check all spam / trash etc - we can see 4 emails going out around that time, only two of which have been opened:

<img width="1094" alt="screenshot 2016-10-19 14 52 32" src="https://cloud.githubusercontent.com/assets/488297/19521507/d15c05e8-960b-11e6-8370-29c26ab2a033.png">

Neil

**Comment by Pikapangokev** [comment]
It appears in my Junk, this account is on my phone, junk does not come through unless I ask it.
Well done, it did send after all.
