### ISSUE TITLE
On holding page the link goes mail chimp registration (not an issue, just an observation)

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#69]
![screen shot 2016-10-14 at 09 49 19](https://cloud.githubusercontent.com/assets/22468878/19382343/b0498c9e-91f7-11e6-9458-13d46d813406.png)

**Comment by Pikapangokev** [comment]
No place for entering phone, company etc

**Comment by Pikapangokev** [comment]
Has anyone registered using this apart from us lot??
How do I find out this info?

**Comment by neilpie** [comment]
This registration just signs people up to the mailing list so we can notify them when we go live. They will need to re-register on the site for an account.

**Comment by neilpie** [comment]
@Pikapangokev just checking that you have login details for Mailchimp

**Comment by Pikapangokev** [comment]
Okay I get it now. I don't have the login details, can you post them please?
