### ISSUE TITLE
FAQ has been replaced with T&C, Can we add FAQ as well? 

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#70]
![img_0946](https://cloud.githubusercontent.com/assets/22468878/19382418/0ac89480-91f8-11e6-8efa-9d0dd2b05b9a.PNG)

**Comment by neilpie** [comment]
Hi @Pikapangokev 

This menu can be edited at http://pikapango.staging.wpengine.com/wp-admin/nav-menus.php?action=edit&menu=4

Any Qs please don't hesitate to give me a shout,
Neil
