### ISSUE TITLE
Add time & date to Quote View

### ISSUE THREAD

**Issue by neilpie** [pie/PikaPango#74]
When the user can view a quote, they are only shown:
- Quote number & postcodes
- Quote title
- Images
- Quote value
- Quote status

Ideally we would like to avoid shpwing the Driver Notes to the client, if we can add other data from the quote to this view, would that solve the problem?

Which other data should be added?

Could time and date be added under ID/Postcode line - is this time & date for collection?
Any other info?

**Comment by Pikapangokev** [comment]
Yes, the time and date will need to be shown to the client at
1) The pay now screen before payment
2) On the email they receive which alerts them that their quote has been updated to pay now status
3) On their invoice

How will I add the time and date without using the drivers notes section?
There is no space to add time at the moment

**Comment by neilpie** [comment]
I would imagine that we take the time and date from the collection info in the quote.

1 & 2 would be an enhancement

3) would be dealt with in #76

**Comment by neilpie** [comment]
have moved point 2) to #110
