### ISSUE TITLE
Re: #31 - Our invoice has no details of the client

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#76]

**Comment by Pikapangokev** [comment]
We need the invoice to have an invoice address, at the moment it is just their name.
1) we must have a proper sign up form recording these full details
2) the avatar blank character in the sidebar should also have the option to upload new photo

Should this be a standard function, as the information is required on invoices anyway? 
Do we have to pay for this upgrade?

**Comment by neilpie** [comment]
From Gov UK

2. Invoices - what they must include
You must clearly display the word ‘invoice’ on the document. You must include:

a unique identification number
your company name, address and contact information
the company name and address of the customer you’re invoicing
a clear description of what you’re charging for
the date the goods or service were provided (supply date)
the date of the invoice
the amount(s) being charged
VAT amount if applicable
the total amount owed

**Comment by neilpie** [comment]
The avatar is hooked in to 'Gravatar' and pulls from there, adding the facility to upload would be an extra

**Comment by neilpie** [comment]
Of note, this address will now be split onto multiple lines if it contains commas
