### ISSUE TITLE
Once a user resets password they have to re enter their Username and Password again

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#79]

**Comment by Pikapangokev** [comment]
Can they go straight to the signed in screen, ready to quote rather than have to do this double task?

**Comment by neilpie** [comment]
No this is a security issue. If a user changes their password, the system logs out *all* of their active sessions and forces a re-entry to ensure that any user using the compromised password is logged out.

If this is a real issue then we can look at working around it but I would certainly advise against it.
