### ISSUE TITLE
Password reset process is extremely frustrating

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#80]

**Comment by Pikapangokev** [comment]
1) It asks for 12 characters, can this be shortened to say 8?
2) If the password isn't considered strong then it will not let you use it - can this be less secure?
(for example most people use a capital letters, lower case letters and numbers. Currently it won't let you do this unless there are a number of symbols thrown in too. I don't want new clients to have to invent a super secure password which takes 3 or 4 attempts to get right).

**Comment by neilpie** [comment]
It looks like this *should* only be in place for administrator & driver accounts and is implemented by the Hosting platfiorm for security. I have raised a ticket with them for now

**Comment by neilpie** [comment]
This is only now in place for drivers & admins. Normal users are shown the strength meter, but it is not enforced.
