### ISSUE TITLE
Terms and conditions and terms of service conflict

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#81]

**Comment by Pikapangokev** [comment]
So on signing up we have to tick I have read the terms and conditions.
Then before submitting quote we have to tick i have read terms of service.

1) I think we should use the phrase terms and conditions through out the site.
2) I think that we shouldn't have to tick this twice, I don't think I do this on any other site. This should be at the summit quote stage only and it should be I confirm that by ticking this box I agree to the Terms and Conditions.
3) on sign up, the tick box should say something along the lines of I am familiar with/have read the Terms and conditions OR take it away from sign up completely

**Comment by neilpie** [comment]
@Pikapangokev 

I remember discussing this previously and it was decided that we needed a tickbox on signup *and* when creating a quote.

No problem if this has now changed but with regards to 3) - which solution do we want?

**Comment by neilpie** [comment]
Please can you review and confirm all is OK now @Pikapangokev

**Comment by neilpie** [comment]
Please ensure both links go to terms gape

**Comment by neilpie** [comment]
@Pikapangokev looking good now
