### ISSUE TITLE
Add a sign up link to homepage

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#89]
I suggest adding it to the bottom under 'get quote button'

**Comment by neilpie** [comment]
LIke this?

<img width="472" alt="screenshot 2016-11-07 21 38 21" src="https://cloud.githubusercontent.com/assets/488297/20077010/89334b92-a532-11e6-9206-c2c57a5bca6a.png">

**Comment by Pikapangokev** [comment]
yes like that
