### ISSUE TITLE
change weight drop-down choices

### ISSUE THREAD

**Issue by neilpie** [pie/PikaPango#9]
Weight now to be drop down menu - see attached image below

**Comment by neilpie** [comment]
Having changed these to the text supplied, there's some overlap. Can we reduce the text slightly?

1000kg  (public road max)
1500kg  (private road max)
2000kg (max lift)

or similar?

**Comment by Pikapango** [comment]
![screen shot 2016-09-27 at 10 03 11](https://cloud.githubusercontent.com/assets/22468878/18866873/a25eef40-8499-11e6-93e0-dff1840163a2.png)
I see what you mean

**Comment by Pikapango** [comment]
The suggestions you have made above would work I think
