### ISSUE TITLE
After entering 2 postcodes on quick quote, change the 'get exact quote' button 

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#91]
Get rid of get exact quote and replace with sign in and sign up buttons.
![screen shot 2016-11-07 at 21 40 18](https://cloud.githubusercontent.com/assets/22468878/20077078/cffbb85c-a532-11e6-94d5-5c28aa4858de.png)
An extra sentence will be needed after the £40 sentence to explain. It should read;
'£40 +VAT Estimate, based on you postcodes only.
If you'd like accurate quote we need to get some 
more information from you. Please either 
SIGN IN       or       SIGN UP'

Or it could read;
'£40 +VAT Estimate, based on you postcodes only.
For an exact quote you will need to
 SIGN IN       or       SIGN UP
and supply more information'

**Comment by neilpie** [comment]
Decided for logged out users:

'£40 +VAT Estimate, based on you postcodes only.
For an exact quote you will need to
SIGN IN or SIGN UP
and supply more information'
