### ISSUE TITLE
Change text in Pop up banner straight after signing up

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#98]
![screen shot 2016-11-07 at 22 04 53](https://cloud.githubusercontent.com/assets/22468878/20078118/2ea3fe56-a537-11e6-9215-6073641fbe89.png)

**Comment by neilpie** [comment]
This issue is partly resolved by #92

**Comment by neilpie** [comment]
Changing this issue to redirect to a thank you page containing the same message.
